---

- name: Verify jupyterhub
  hosts: "{{ playbook_hosts | default('all') }}"
  vars:
    test_pkg: nodejs
    exec_file: /export/jupyterhub/bin/jupyter
    processes:
      - { u: root, p: python }
    ports:
      - { h: localhost, p: 8000 }
    is_container: false
  pre_tasks:
    - name: RedHat | Ensure ps and host are present
      ansible.builtin.package:
        name:
          - procps-ng
          - bind-utils
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
    - name: Debian | Ensure ps and host present
      ansible.builtin.package:
        name:
          - procps
          - dnsutils
        state: present
      when: ansible_os_family == "Debian"
    - name: Debug | var ansible_virtualization_type
      ansible.builtin.debug:
        var: ansible_virtualization_type
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when: >
        (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker"
           or ansible_virtualization_type == "containerd"
           or ansible_virtualization_type == "container"
          )
        )
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that: ansible_facts.packages[test_pkg]

    - name: Check executable
      ansible.builtin.stat:
        path: "{{ exec_file }}"
      register: bin1
    - name: Validate executable is present
      ansible.builtin.assert:
        that:
          - bin1.stat.exists and bin1.stat.size != 0 and bin1.stat.mode == '0755'

    - name: Ensure processes are running
      ansible.builtin.command:
        cmd: "pgrep -u {{ item.u }} {{ item.p }}"
      register: ps
      changed_when: false
      failed_when: false
      loop: "{{ processes }}"
    - name: Debug | var ps
      ansible.builtin.debug:
        var: ps
    - name: Validate ps output
      ansible.builtin.assert:
        that:
          - item.stdout | length > 0
      loop: "{{ ps.results }}"
      when:
        - not is_container|bool

    - name: Check all processes
      ansible.builtin.command: ps aux
      changed_when: false
      register: psa
    - name: Debug | ps aux output
      ansible.builtin.debug:
        var: psa
        verbosity: 1

    - name: Ensure ports are listening
      ansible.builtin.wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items: "{{ ports }}"
      when:
        - not is_container|bool

    - name: Get journald errors
      ansible.builtin.command:
        cmd: journalctl -u jupyterhub -g Error -l --no-pager
      changed_when: false
      failed_when: false
      register: journald
      become: true
    - name: Ensure journald has no errors
      ansible.builtin.assert:
        that:
          - journald.stderr | length == 0 or journald.stderr == "No journal files were found."
          - journald.stdout == "-- No entries --"
